name: Build and upload artifact

on: 
    workflow_dispatch: 
    #[push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Set up MSVC
              uses: ilammy/msvc-dev-cmd@v1
            - name: Configure CMake
              run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
            - name: Build
              run: cmake --build build --config Release --target bnusio
            - uses: actions/upload-artifact@v4
              with:
                  name: TaikoArcadeLoader
                  path: dist/
                  compression-level: 9
